apiVersion: v1
kind: Service
metadata:
  labels:
    name: requestcounterservice
  name: requestcounterservice
  namespace: frontend
spec:
  ports:
    # The port that this service should serve on.
   - protocol: TCP
     port: 8091
     targetPort: 8091
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    app: request-counter-ms
  type: NodePort
